(()=>{
'use strict';
const BUILD='1.3.2';
const TOKEN='mh_social_token_v1';
const PROFILE=()=>localStorage.getItem('mh_active_profile_v1')||'default';
const key=k=>`mh:${PROFILE()}:${k}`;
const $=s=>document.querySelector(s);
const $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const read=(k,d)=>{try{const x=JSON.parse(localStorage.getItem(k));return x==null?d:x}catch{return d}};
const write=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v));window.mhScheduleCloudSync?.()}catch{}};
const signedIn=()=>!!(localStorage.getItem(TOKEN)&&window.mhSocialSignedIn?.());
const token=()=>localStorage.getItem(TOKEN)||'';
let currentGame=null,saveBaseline=null,notifyTimer=null,gameParty=null,gamePartyTimer=null,lastGamePartyLaunch=0;
const platformCall=async(action,data={})=>{const r=await fetch('/api/platform-api',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+token()},body:JSON.stringify({action,...data}),cache:'no-store'});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'Request failed');return j;};
const socialCall=async(action,data={})=>{const r=await fetch('/api/social-api',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+token()},body:JSON.stringify({action,...data}),cache:'no-store'});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'Request failed');return j;};
function toast(t,i='✓'){window.showToast?.(t,i)}
function fmtSec(sec){sec=Math.max(0,Math.floor(Number(sec)||0));const h=Math.floor(sec/3600),m=Math.floor((sec%3600)/60);return h?`${h}h ${m}m`:`${m}m`;}

// ---------- XP, levels, achievements ----------
const XP_KEY=()=>key('platform_xp_v1');
const ACH_KEY=()=>key('platform_achievements_v1');
function xpData(){return read(XP_KEY(),{xp:0,awards:{},daily:'',secrets:[]});}
function levelInfo(xp){let level=1,need=100,left=xp;while(left>=need&&level<100){left-=need;level++;need=100+(level-1)*50;}return{level,current:left,need,total:xp,progress:Math.min(100,left/need*100)};}
const PLATFORM_ACH=[
 ['first_game','🎮','First Game','Launch a game.'],['ten_games','🕹️','Arcade Regular','Launch 10 games.'],['hour','⏱️','Locked In','Reach one hour of game time.'],['social','👥','Social Butterfly','Have at least 3 friends.'],['secret','🔐','Secret Finder','Find a secret code.'],['tv','📺','Channel Surfer','Open 10 Live TV channels.'],['movie','🍿','Movie Night','Start 3 Movies or TV titles.'],['offline','📦','Ready Offline','Cache a game for offline use.'],['party','🎉','Party Up','Create or join a Nova Math party.'],['level10','🏆','Double Digits','Reach level 10.']
];
function achData(){return read(ACH_KEY(),{});}
function unlockAch(id){const all=achData();if(all[id])return;const a=PLATFORM_ACH.find(x=>x[0]===id);if(!a)return;all[id]={at:Date.now()};write(ACH_KEY(),all);toast(`Achievement: ${a[2]}`,a[1]);renderHomeUpgrade();}
function awardXP(amount,reason,unique=''){const d=xpData(),day=new Date().toISOString().slice(0,10),awardKey=unique?`${day}:${unique}`:'';if(awardKey&&d.awards[awardKey])return false;if(awardKey)d.awards[awardKey]=Date.now();d.xp+=Math.max(0,Math.floor(amount));write(XP_KEY(),d);const li=levelInfo(d.xp);if(li.level>=10)unlockAch('level10');toast(`+${amount} XP · ${reason}`,'✦');renderHomeUpgrade();return true;}
function dailyXP(){const d=xpData(),today=new Date().toISOString().slice(0,10);if(d.daily!==today){d.daily=today;d.xp+=20;write(XP_KEY(),d);setTimeout(()=>toast('+20 XP · Daily visit','✦'),1200);}}
function evaluateAchievements(){const st=read(key('game_stats'),{}),entries=Object.values(st),launches=entries.reduce((a,b)=>a+(b.launches||0),0),secs=entries.reduce((a,b)=>a+(b.seconds||0),0);if(launches)unlockAch('first_game');if(launches>=10)unlockAch('ten_games');if(secs>=3600)unlockAch('hour');const li=levelInfo(xpData().xp);if(li.level>=10)unlockAch('level10');}

// ---------- Notification center ----------
function ensureNotifications(){
 if($('#mhNotifyBtn'))return;
 const tools=$('.hub-tools');if(!tools)return;
 const btn=document.createElement('button');btn.id='mhNotifyBtn';btn.className='mh-notify-btn';btn.type='button';btn.innerHTML='<span>🔔</span><span class="hub-tool-label">Alerts</span><b id="mhNotifyBadge" hidden>0</b>';btn.onclick=openNotifications;tools.prepend(btn);
 const panel=document.createElement('section');panel.id='mhNotifyPanel';panel.className='mh-notify-panel';panel.hidden=true;panel.innerHTML='<div class="mh-panel-head"><div><small>NOVA MATH</small><strong>Notifications</strong></div><div><button id="mhNotifyReadAll">Mark read</button><button id="mhNotifyClose">×</button></div></div><div id="mhNotifyList" class="mh-notify-list"></div>';document.body.appendChild(panel);
 $('#mhNotifyClose').onclick=()=>panel.hidden=true;$('#mhNotifyReadAll').onclick=async()=>{if(signedIn())try{await socialCall('notifications-read-all');await refreshNotifications()}catch{};};
 document.addEventListener('click',e=>{if(!panel.hidden&&!panel.contains(e.target)&&!btn.contains(e.target))panel.hidden=true;});
}
async function refreshNotifications(){ensureNotifications();const list=$('#mhNotifyList'),badge=$('#mhNotifyBadge');let items=[];let unread=0;
 try{const ann=await platformCall('announcements');for(const a of ann.items||[])items.push({id:'ann-'+a.id,type:'announcement',title:a.title,body:a.body,at:a.at||0,read:true});}catch{}
 if(signedIn())try{const n=await socialCall('notifications');items.push(...(n.items||[]));unread=n.unread||0;}catch{}
 items.sort((a,b)=>(b.at||0)-(a.at||0));if(badge){badge.hidden=!unread;badge.textContent=unread>99?'99+':String(unread)}
 if(list)list.innerHTML=items.length?items.slice(0,60).map(n=>`<button class="mh-notification ${n.read?'':'unread'}" data-id="${esc(n.id)}" data-type="${esc(n.type||'')}" data-code="${esc(n.data?.partyCode||n.data?.code||'')}"><span>${n.type==='message'?'✉':n.type==='game'?'🎮':(n.type==='party'||n.type==='watch-party')?'🎉':n.type==='friend'?'👥':n.type==='snack'?'🍿':'📣'}</span><div><strong>${esc(n.title)}</strong><p>${esc(n.body||'')}</p><small>${n.at?new Date(n.at).toLocaleString():''}</small></div></button>`).join(''):'<div class="mh-empty">No new notifications.</div>';
 list?.querySelectorAll('.mh-notification[data-id]').forEach(el=>el.onclick=async()=>{const id=el.dataset.id,type=el.dataset.type,partyCode=el.dataset.code;if(id&&!id.startsWith('ann-')&&signedIn())try{await socialCall('notification-read',{id});el.classList.remove('unread')}catch{};if(type==='message'||type==='friend')window.mhSocialOpen?.();else if((type==='party'||type==='watch-party')&&partyCode){openGameParty();setTimeout(()=>{const i=$('#mhGPJoinCode');if(i){i.value=partyCode;joinGameParty(partyCode)}},60)}else if(type==='game')window.mhSocialOpen?.();refreshNotifications();});
}
function openNotifications(){ensureNotifications();const p=$('#mhNotifyPanel');p.hidden=!p.hidden;if(!p.hidden)refreshNotifications();}

// ---------- Personal home ----------
function renderHomeUpgrade(){const tab=$('#tab-arcade'),hero=$('#arcadeHero');if(!tab||!hero)return;let sec=$('#mhPersonalHome');if(!sec){sec=document.createElement('section');sec.id='mhPersonalHome';sec.className='mh-personal-home';hero.after(sec);}const stats=read(key('game_stats'),{}),games=window.BUILT_IN_GAMES||[],map=new Map(games.map(g=>[g.file,g])),recent=Object.entries(stats).sort((a,b)=>(b[1].lastPlayed||0)-(a[1].lastPlayed||0)).slice(0,6).map(([f,s])=>map.get(f)||{file:f,title:s.title||f}),favs=read(key('my_games'),[]).slice(0,6).map(f=>map.get(f)).filter(Boolean),li=levelInfo(xpData().xp),resume=read(key('movie_resume'),{});const mini=(title,rows)=>rows.length?`<div class="mh-home-row"><div class="mh-row-heading"><strong>${title}</strong><button onclick="window.switchTab?.('arcade',document.querySelector('[data-tab=arcade]'))">See games</button></div><div class="mh-mini-games">${rows.map(g=>`<button data-file="${esc(g.file)}"><span>▶</span><strong>${esc(g.title)}</strong></button>`).join('')}</div></div>`:'';sec.innerHTML=`<div class="mh-home-top"><div><small>NOVA MATH</small><h2>Home</h2></div><button onclick="mhOpenStats()">Level ${li.level} · ${li.total} XP</button></div><div class="mh-home-metrics"><button onclick="mhOpenStats()"><b>${li.level}</b><span>Level</span></button><button onclick="window.mhSocialOpen?.()"><b id="mhHomeOnline">…</b><span>Friends online</span></button><button onclick="mhOpenStats()"><b>${favs.length}</b><span>Saved games</span></button><button onclick="window.switchTab?.('movies',document.querySelector('[data-tab=movies]'))"><b>${Object.keys(resume).length}</b><span>Continue watching</span></button></div><div id="mhHomeFriends" class="mh-home-friends" hidden></div>${mini('Continue Playing',recent)}${mini('Favorites',favs)}`;sec.querySelectorAll('[data-file]').forEach(b=>b.onclick=()=>openGameDetails(map.get(b.dataset.file)||{file:b.dataset.file,title:b.querySelector('strong').textContent,genre:'Game'}));if(signedIn())socialCall('friend-presence').then(j=>{const online=(j.items||[]).filter(x=>x.online),el=$('#mhHomeOnline'),row=$('#mhHomeFriends');if(el)el.textContent=String(online.length);if(row&&online.length){row.hidden=false;row.innerHTML='<strong>Friends online</strong><div>'+online.slice(0,8).map(x=>`<button onclick="window.mhSocialOpen?.()"><span>${esc(x.user.avatar)}</span><b>${esc(x.user.displayName)}</b><small>${esc(x.activity||'Online')}</small></button>`).join('')+'</div>';}}).catch(()=>{});}


// ---------- Game details, offline caching, save sync ----------
function ensureGameDetails(){if($('#mhGameDetail'))return;const m=document.createElement('section');m.id='mhGameDetail';m.className='mh-platform-modal';m.hidden=true;m.innerHTML='<div class="mh-game-detail-card"><button class="mh-modal-x" data-close>×</button><div id="mhGameDetailBody"></div></div>';document.body.appendChild(m);m.querySelector('[data-close]').onclick=()=>m.hidden=true;m.addEventListener('click',e=>{if(e.target===m)m.hidden=true;});}
function gameStat(file){return read(key('game_stats'),{})[file]||{};}
function gameSaved(file){return read(key('my_games'),[]).includes(file);}
function gameSaveMap(){return read(key('game_save_sync_v1'),{});}
function gameArtFor(file){const c=read('mh_game_art_cache_v7_poster',{});const vals=Object.values(c);return vals.find(x=>x&&x.url&&String(x.gameName||'').length)?.url||'';}
function openGameDetails(game){if(!game?.file)return;ensureGameDetails();const st=gameStat(game.file),local=/^(\/?docs\/)/i.test(game.file),saved=gameSaved(game.file),save=gameSaveMap()[game.file],m=$('#mhGameDetail'),body=$('#mhGameDetailBody');m.hidden=false;body.innerHTML=`<div class="mh-game-detail-hero" style="--h:${Number(game.hue||220)}"><div class="mh-game-detail-art"><div>${esc(game.title)}</div></div><div><small>${esc(game.genre||'Arcade')}</small><h2>${esc(game.title)}</h2><p>Built into Nova Math${local?' · Offline-capable after caching':''}</p><div class="mh-game-detail-actions"><button class="primary" id="mhGPlay">▶ Play</button><button id="mhGFav">${saved?'★ Saved':'☆ Save'}</button>${local?'<button id="mhGOffline">↓ Cache offline</button>':''}</div></div></div><div class="mh-detail-grid"><div><span>Playtime</span><strong>${fmtSec(st.seconds||0)}</strong></div><div><span>Launches</span><strong>${st.launches||0}</strong></div><div><span>Last played</span><strong>${st.lastPlayed?new Date(st.lastPlayed).toLocaleDateString():'Never'}</strong></div><div><span>Save sync</span><strong>${save?'Stored':'Compatible games only'}</strong></div></div><div class="mh-detail-note"><strong>Controls</strong><p>Keyboard, mouse, touch, or controller support depends on the game. Escape closes the Nova Math player. Compatible localStorage save changes are backed up per game when possible.</p></div><div class="mh-game-detail-bottom"><button id="mhGParty">🎉 Game Party</button><button onclick="mhOpenStats()">Stats</button></div>`;
 $('#mhGPlay').onclick=()=>{m.hidden=true;window.openGame?.(game)};$('#mhGFav').onclick=()=>{const a=read(key('my_games'),[]),on=a.includes(game.file),next=on?a.filter(x=>x!==game.file):[game.file,...a].slice(0,100);write(key('my_games'),next);if(!on)awardXP(4,'Saved a game',`fav:${game.file}`);openGameDetails(game);};$('#mhGOffline')?.addEventListener('click',()=>cacheGame(game));$('#mhGParty').onclick=()=>{m.hidden=true;openGameParty(game);};}
async function cacheGame(game){try{const u=new URL(game.file,location.href);const r=await fetch(u,{cache:'reload'});if(!r.ok)throw new Error('Game file did not load');const c=await caches.open('mediahub-games-v9-v74');await c.put(u,r.clone());unlockAch('offline');awardXP(8,'Cached a game',`offline:${game.file}`);toast('Game entry cached for offline play','📦');}catch(e){toast('Offline cache failed','⚠')}}
function localSnapshot(){const out={};try{for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(!k||k.startsWith('mh:')||k.startsWith('mh_')||k.startsWith('mediahub_')||k.includes('token')||k.includes('auth'))continue;const v=localStorage.getItem(k);if(v!=null&&v.length<120000)out[k]=v;}}catch{}return out;}
function restoreGameSave(file){const data=gameSaveMap()[file]?.values;if(!data)return;try{for(const [k,v] of Object.entries(data))localStorage.setItem(k,v)}catch{}}
function saveGameDiff(file){if(!file||!saveBaseline)return;const after=localSnapshot(),changed={};for(const [k,v] of Object.entries(after))if(saveBaseline[k]!==v)changed[k]=v;if(!Object.keys(changed).length)return;const all=gameSaveMap();all[file]={values:{...(all[file]?.values||{}),...changed},updatedAt:Date.now()};let str=JSON.stringify(all[file]);if(str.length>240000){all[file].values=Object.fromEntries(Object.entries(all[file].values).slice(-120));}write(key('game_save_sync_v1'),all);}
function patchGames(){if(typeof window.openGame==='function'&&!window.openGame.__platform69){const base=window.openGame;const wrap=function(game,...rest){currentGame=game||null;restoreGameSave(game?.file);saveBaseline=localSnapshot();awardXP(6,'Played a game',`play:${game?.file||'game'}`);platformCall('event',{type:'game_launch',gameFile:game?.file||'',title:game?.title||''}).catch(()=>{});const r=base.call(this,game,...rest);setTimeout(evaluateAchievements,1000);return r};wrap.__platform69=true;window.openGame=wrap;}if(typeof window.closeGamePlayer==='function'&&!window.closeGamePlayer.__platform69){const base=window.closeGamePlayer;const wrap=function(...args){if(currentGame?.file)saveGameDiff(currentGame.file);currentGame=null;saveBaseline=null;const r=base.apply(this,args);renderHomeUpgrade();return r};wrap.__platform69=true;window.closeGamePlayer=wrap;}}
function interceptGameCards(){document.addEventListener('click',e=>{const card=e.target.closest?.('.netflix-game-card');if(!card||e.defaultPrevented)return;const g=(window.BUILT_IN_GAMES||[]).find(x=>x.file===card.dataset.gameFile);if(!g)return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();openGameDetails(g);},true);}

// ---------- Global search ----------
function ensureSearch(){if($('#mhPlatformSearch'))return;const m=document.createElement('section');m.id='mhPlatformSearch';m.className='mh-platform-search';m.hidden=true;m.innerHTML='<div class="mh-search-card"><div class="mh-search-input"><span>⌕</span><input id="mhPlatformSearchInput" placeholder="Search games, movies, TV, friends, apps, settings…"><kbd>ESC</kbd></div><div id="mhPlatformSearchResults" class="mh-search-results"></div></div>';document.body.appendChild(m);m.addEventListener('click',e=>{if(e.target===m)m.hidden=true;});$('#mhPlatformSearchInput').addEventListener('input',e=>renderSearch(e.target.value));}
function openSearch(){ensureSearch();const m=$('#mhPlatformSearch');m.hidden=false;const i=$('#mhPlatformSearchInput');i.value='';renderSearch('');setTimeout(()=>i.focus(),20);}
async function renderSearch(q){const out=$('#mhPlatformSearchResults'),text=String(q||'').trim().toLowerCase(),items=[];const add=(icon,title,sub,run)=>items.push({icon,title,sub,run});
 for(const g of (window.BUILT_IN_GAMES||[]).filter(g=>!text||`${g.title} ${g.genre||''}`.toLowerCase().includes(text)).slice(0,text?8:4))add('🎮',g.title,g.genre||'Game',()=>openGameDetails(g));
 const tabs=[['Movies & TV','movies','🍿'],['Music','music','♫'],['Live TV','livetv','📺'],['Sports','sports','🏈'],['Food & Drinks','food','🥡'],['Apps','apps','▦'],['Games','arcade','🕹️']];for(const [title,id,icon] of tabs)if(!text||title.toLowerCase().includes(text))add(icon,title,'Open section',()=>window.switchTab?.(id,document.querySelector(`[data-tab="${id}"]`)));
 if(text){add('🍿',`Search Movies & TV for “${q}”`,'TMDB catalog',()=>{window.switchTab?.('movies',document.querySelector('[data-tab="movies"]'));setTimeout(()=>{const i=$('#tmdb-search-input');if(i){i.value=q;window.searchTMDb?.()}},150)});add('♫',`Search Music for “${q}”`,'All music sources',()=>{window.switchTab?.('music',document.querySelector('[data-tab="music"]'));setTimeout(()=>{const i=$('#music-search-input')||$('#tidalSearchInput');if(i){i.value=q;window.searchAllMusic?.()}},150)});}
 const live=window.mhGetLiveTvState?.()?.channels||[];for(const c of live.filter(c=>text&&`${c.name} ${c.group||''}`.toLowerCase().includes(text)).slice(0,6))add('📺',c.name,c.group||'Live TV',()=>{window.switchTab?.('livetv',document.querySelector('[data-tab="livetv"]'));setTimeout(()=>window.mhPlayIptvChannel?.(c),250)});
 if(text&&window.mhSportsSearch){for(const r of window.mhSportsSearch(q)||[])add(r.icon||'🏈',r.title,r.subtitle||'Sports',r.run);}
 if(text&&signedIn())try{const r=await socialCall('find',{username:text});if(r.user)add('👤',r.user.displayName,'@'+r.user.username,()=>window.mhSocialOpen?.())}catch{}
 const settings=[['Themes','Theme Store',openThemeStore],['Stats','Account Stats',openStats],['Friends','Friends & Messages',()=>window.mhSocialOpen?.()],['Report','Report a Problem',()=>{window.openMediaHubSettings?.();setTimeout(()=>document.getElementById('mhReportSubject')?.focus(),100)}],['Admin','Admin Dashboard',openAdmin]];for(const [match,title,run] of settings)if(!text||`${match} ${title}`.toLowerCase().includes(text))add('⚙',title,'Nova Math',run);
 out.innerHTML=items.length?items.slice(0,24).map((x,i)=>`<button data-i="${i}"><span>${x.icon}</span><div><strong>${esc(x.title)}</strong><small>${esc(x.sub)}</small></div><em>↵</em></button>`).join(''):'<div class="mh-empty">No results.</div>';out.querySelectorAll('[data-i]').forEach(b=>b.onclick=()=>{const x=items[Number(b.dataset.i)];$('#mhPlatformSearch').hidden=true;x?.run?.();});}

// ---------- Themes ----------
const THEME_KEY=()=>key('platform_theme_v1');
const themes=[['midnight','Midnight','🌑',1],['oled','OLED','⬛',1],['yellow','Yellow','🟨',1],['purple','Purple','🟪',2],['retro','Retro','🕹️',3],['xbox','Xbox','🟢',4],['playstation','PlayStation','🔵',5],['gamecube','GameCube','🟣',6],['xp','Windows XP','🖥️',7],['glass','Glass','◈',8]];
function applyPlatformTheme(){document.documentElement.dataset.mhTheme69=localStorage.getItem(THEME_KEY())||'midnight';}
function unlockedThemes(){const l=levelInfo(xpData().xp).level,secrets=xpData().secrets||[];return new Set(themes.filter(t=>t[3]<=l||secrets.includes(t[0])).map(t=>t[0]));}
function openThemeStore(){let m=$('#mhThemeStore');if(!m){m=document.createElement('section');m.id='mhThemeStore';m.className='mh-platform-modal';m.hidden=true;m.innerHTML='<div class="mh-standard-card"><button class="mh-modal-x">×</button><small>PERSONALIZATION</small><h2>Theme Store</h2><p>Unlock themes by leveling up and finding secret codes.</p><div id="mhThemeGrid" class="mh-theme-grid"></div></div>';document.body.appendChild(m);m.querySelector('.mh-modal-x').onclick=()=>m.hidden=true;m.addEventListener('click',e=>{if(e.target===m)m.hidden=true;});}const unlocked=unlockedThemes(),current=localStorage.getItem(THEME_KEY())||'midnight';$('#mhThemeGrid').innerHTML=themes.map(t=>`<button data-theme="${t[0]}" class="${current===t[0]?'active':''} ${unlocked.has(t[0])?'':'locked'}"><span>${t[2]}</span><strong>${t[1]}</strong><small>${unlocked.has(t[0])?(current===t[0]?'Active':'Unlocked'):`Level ${t[3]}`}</small></button>`).join('');$('#mhThemeGrid').querySelectorAll('[data-theme]').forEach(b=>b.onclick=()=>{if(!unlocked.has(b.dataset.theme)){toast('Keep leveling up to unlock this theme','🔒');return;}localStorage.setItem(THEME_KEY(),b.dataset.theme);window.mhScheduleCloudSync?.();applyPlatformTheme();openThemeStore();});m.hidden=false;}

// ---------- Stats and profile ----------
function statSummary(){const stats=read(key('game_stats'),{}),entries=Object.values(stats),gameSec=entries.reduce((a,b)=>a+(b.seconds||0),0),launches=entries.reduce((a,b)=>a+(b.launches||0),0),top=Object.entries(stats).sort((a,b)=>(b[1].seconds||0)-(a[1].seconds||0))[0],map=new Map((window.BUILT_IN_GAMES||[]).map(g=>[g.file,g.title]));return{gameSec,launches,top:top?(map.get(top[0])||top[1].title||top[0]):'None',movies:Object.keys(read(key('movie_resume'),{})).length,tvChannels:(read(key('platform_tv_history_v1'),[])||[]).length,friends:0,ach:Object.keys(achData()).length};}
async function openStats(){let m=$('#mhStatsModal');if(!m){m=document.createElement('section');m.id='mhStatsModal';m.className='mh-platform-modal';m.hidden=true;m.innerHTML='<div class="mh-standard-card mh-stats-card"><button class="mh-modal-x">×</button><div id="mhStatsBody"></div></div>';document.body.appendChild(m);m.querySelector('.mh-modal-x').onclick=()=>m.hidden=true;}m.hidden=false;const s=statSummary(),li=levelInfo(xpData().xp),achs=achData(),stats=read(key('game_stats'),{}),map=new Map((window.BUILT_IN_GAMES||[]).map(g=>[g.file,g.title])),recent=Object.entries(stats).sort((a,b)=>(b[1].lastPlayed||0)-(a[1].lastPlayed||0)).slice(0,8).map(([f,x])=>map.get(f)||x.title||f),favorites=read(key('my_games'),[]).slice(0,8).map(f=>map.get(f)||f);let friends='—',profile=null;if(signedIn())try{const [f,me]=await Promise.all([socialCall('friends'),socialCall('me')]);friends=(f.items||[]).filter(x=>x.relationship?.status==='friends').length;profile=me.user;if(friends>=3)unlockAch('social')}catch{}const badges=PLATFORM_ACH.filter(a=>achs[a[0]]).slice(0,6);$('#mhStatsBody').innerHTML=`<div class="mh-profile-banner banner-${esc(profile?.banner||'midnight')}"><span>${esc(profile?.avatar||'🎮')}</span><div><small>${profile?'@'+esc(profile.username):'LOCAL PROFILE'}</small><h2>${esc(profile?.displayName||'Nova Math Profile')}</h2><p>${esc(profile?.customStatus||'')}</p><div class="mh-profile-badges">${badges.map(a=>`<span title="${esc(a[2])}">${a[1]}</span>`).join('')}</div></div></div><div class="mh-level-box"><div><strong>Level ${li.level}</strong><span>${li.current}/${li.need} XP</span></div><i><b style="width:${li.progress}%"></b></i></div><div class="mh-stats-grid"><div><b>${fmtSec(s.gameSec)}</b><span>Game time</span></div><div><b>${s.launches}</b><span>Game launches</span></div><div><b>${esc(s.top)}</b><span>Most played</span></div><div><b>${s.movies}</b><span>Watch history</span></div><div><b>${friends}</b><span>Friends</span></div><div><b>${Object.keys(achs).length}/${PLATFORM_ACH.length}</b><span>Achievements</span></div>${profile?.createdAt?`<div><b>${new Date(profile.createdAt).toLocaleDateString()}</b><span>Joined</span></div>`:''}</div><div class="mh-profile-lists"><section><h3>Favorite Games</h3>${favorites.length?favorites.map(x=>`<span>${esc(x)}</span>`).join(''):'<span>No favorites yet.</span>'}</section><section><h3>Recently Played</h3>${recent.length?recent.map(x=>`<span>${esc(x)}</span>`).join(''):'<span>No recent games yet.</span>'}</section></div><h3>Achievements</h3><div class="mh-ach-grid">${PLATFORM_ACH.map(a=>`<div class="${achs[a[0]]?'unlocked':'locked'}"><span>${a[1]}</span><strong>${a[2]}</strong><small>${a[3]}</small></div>`).join('')}</div><div class="mh-profile-actions"><button onclick="mhOpenThemeStore()">Theme Store</button><button onclick="window.mhSocialOpen?.()">Friends & Profile</button></div>`;}


// ---------- Secret upgrades ----------
function patchSecrets(){const base=window.mhTrySecretCode;if(!base||base.__platform69)return;const wrap=function(value){const code=String(value||'').trim(),map={'1985':['retro','Retro theme unlocked'],'3600':['xbox','Xbox theme unlocked'],'2001':['gamecube','GameCube theme unlocked'],'2468':['glass','Glass theme unlocked'],'7777':['purple','Purple theme unlocked']};if(code==='4040'){document.body.classList.add('mh-secret-crt');setTimeout(()=>document.body.classList.remove('mh-secret-crt'),60000);unlockAch('secret');awardXP(35,'Secret code','secret:4040');toast('CRT mode for 60 seconds','📺');return true;}if(map[code]){const d=xpData();if(!d.secrets.includes(map[code][0]))d.secrets.push(map[code][0]);write(XP_KEY(),d);unlockAch('secret');awardXP(35,'Secret code',`secret:${code}`);toast(map[code][1],'🔐');const i=$('#mhSecretCode');if(i)i.value='';return true;}const ok=base(value);if(ok){unlockAch('secret');awardXP(35,'Secret code','secret:6753');}return ok};wrap.__platform69=true;window.mhTrySecretCode=wrap;}

// ---------- Game parties ----------
function ensureGameParty(){if($('#mhGamePartyModal'))return;const m=document.createElement('section');m.id='mhGamePartyModal';m.className='mh-platform-modal';m.hidden=true;m.innerHTML='<div class="mh-standard-card mh-party-card"><button class="mh-modal-x">×</button><div id="mhGamePartyBody"></div></div>';document.body.appendChild(m);m.querySelector('.mh-modal-x').onclick=()=>m.hidden=true;}
function openGameParty(game=null){ensureGameParty();$('#mhGamePartyModal').hidden=false;if(!signedIn()){const b=$('#mhGamePartyBody');b.innerHTML='<small>MULTIPLAYER</small><h2>Game Party</h2><p>Sign in to create or join parties, chat, invite friends, and sync launches.</p><button class="primary" id="mhGPSignIn">Open account</button>';$('#mhGPSignIn').onclick=()=>{ $('#mhGamePartyModal').hidden=true; window.mhSocialOpen?.(); };return;}if(game&&!gameParty)renderGamePartyCreate(game);else renderGameParty();}
function renderGamePartyCreate(game){const b=$('#mhGamePartyBody');if(!game){b.innerHTML='<div class="mh-empty">Open a game detail page first, or join with a party code.</div><div class="mh-party-join"><input id="mhGPJoinCode" maxlength="6" placeholder="PARTY CODE"><button id="mhGPJoin">Join existing</button></div>';$('#mhGPJoin').onclick=()=>joinGameParty($('#mhGPJoinCode').value);return;}b.innerHTML=`<small>MULTIPLAYER</small><h2>Game Party</h2><p>Launch the same Nova Math game together. If the game has its own lobby code, share it here so everyone joins the real in-game room.</p><div class="mh-party-game"><span>🎮</span><strong>${esc(game.title)}</strong></div><label>Optional in-game room code<input id="mhGPManualRoom" maxlength="40" placeholder="Example: AB12CD"></label><button class="primary" id="mhGPCreate">Create party</button><div class="mh-party-join"><input id="mhGPJoinCode" maxlength="6" placeholder="PARTY CODE"><button id="mhGPJoin">Join existing</button></div>`;$('#mhGPCreate').onclick=async()=>{try{const j=await platformCall('game-party-create',{gameFile:game.file,gameTitle:game.title,roomCode:$('#mhGPManualRoom').value});gameParty=j.party;lastGamePartyLaunch=gameParty.launch?.seq||0;startGameParty();unlockAch('party');awardXP(15,'Created a party','party-create');renderGameParty()}catch(e){alert(e.message)}};$('#mhGPJoin').onclick=()=>joinGameParty($('#mhGPJoinCode').value);}
async function joinGameParty(c){try{const j=await platformCall('game-party-join',{code:String(c||'').toUpperCase()});gameParty=j.party;lastGamePartyLaunch=gameParty.launch?.seq||0;startGameParty();unlockAch('party');awardXP(10,'Joined a party','party-join');renderGameParty()}catch(e){alert(e.message)}}
function renderGameParty(){if(!gameParty){const recent=Object.entries(read(key('game_stats'),{})).sort((a,b)=>(b[1].lastPlayed||0)-(a[1].lastPlayed||0))[0];const g=recent&&(window.BUILT_IN_GAMES||[]).find(x=>x.file===recent[0]);return renderGamePartyCreate(g||(window.BUILT_IN_GAMES||[])[0]);}const me=window.mhSocialGetUser?.(),members=gameParty.members||[],mine=members.find(x=>x.user.id===me?.id),host=gameParty.hostId===me?.id,b=$('#mhGamePartyBody');b.innerHTML=`<small>GAME PARTY · ${esc(gameParty.code)}</small><h2>${esc(gameParty.game.title)}</h2><div class="mh-party-code-row"><strong>${esc(gameParty.code)}</strong><button id="mhGPCopyParty">Copy party code</button></div><div class="mh-party-members">${members.map(x=>`<div class="${x.online?'online':''}"><span>${esc(x.user.avatar)}</span><strong>${esc(x.user.displayName)}</strong><small>${x.host?'Leader':x.ready?'Ready':'Not ready'}</small></div>`).join('')}</div><div class="mh-party-room"><label>In-game room code<input id="mhGPRoom" value="${esc(gameParty.roomCode||'')}" ${host?'':'disabled'}></label>${host?'<button id="mhGPSaveRoom">Save</button>':''}${gameParty.roomCode?'<button id="mhGPCopyRoom">Copy code</button>':''}</div><div class="mh-party-actions"><button id="mhGPReady" class="${mine?.ready?'active':''}">${mine?.ready?'Ready ✓':'Ready up'}</button>${host?'<button id="mhGPLaunch" class="primary">Launch for party</button>':''}<button id="mhGPLeave">Leave</button></div><section class="mh-party-invite"><div class="mh-party-section-title">Invite friends</div><div id="mhGPFriends" class="mh-party-friends"><span>Loading friends…</span></div></section><div class="mh-party-chat"><div id="mhGPChat">${(gameParty.chat||[]).map(x=>`<p><b>${esc(x.avatar)} ${esc(x.name)}</b> ${esc(x.text)}</p>`).join('')||'<span>No messages yet.</span>'}</div><div><input id="mhGPChatInput" maxlength="400" placeholder="Party chat"><button id="mhGPSend">Send</button></div></div><p class="mh-detail-note">Nova Math syncs the game launch. Exact multiplayer session joining only happens when the game itself supports the shared room code or join link.</p>`;$('#mhGPCopyParty').onclick=()=>navigator.clipboard?.writeText(gameParty.code).then(()=>toast('Party code copied','📋')).catch(()=>{});$('#mhGPReady').onclick=()=>gpAction('game-party-ready',{ready:!mine?.ready});$('#mhGPLaunch')?.addEventListener('click',()=>gpAction('game-party-launch'));$('#mhGPSaveRoom')?.addEventListener('click',()=>gpAction('game-party-room',{roomCode:$('#mhGPRoom').value}));$('#mhGPCopyRoom')?.addEventListener('click',()=>navigator.clipboard?.writeText(gameParty.roomCode));$('#mhGPSend').onclick=()=>{const i=$('#mhGPChatInput'),t=i.value.trim();if(t){i.value='';gpAction('game-party-chat',{text:t})}};$('#mhGPLeave').onclick=leaveGameParty;loadGamePartyFriends();}
async function loadGamePartyFriends(){const box=$('#mhGPFriends');if(!box||!gameParty)return;try{const j=await socialCall('friends');const rows=(j.items||[]).filter(x=>x.relationship?.status==='friends');box.innerHTML=rows.length?rows.map(x=>`<button data-u="${esc(x.user.id)}"><span>${esc(x.user.avatar)}</span><strong>${esc(x.user.displayName)}</strong><small>Invite</small></button>`).join(''):'<span>Add friends first.</span>';box.querySelectorAll('[data-u]').forEach(btn=>btn.onclick=async()=>{btn.disabled=true;try{await platformCall('game-party-invite',{code:gameParty.code,userId:btn.dataset.u});btn.querySelector('small').textContent='Sent ✓';}catch(e){btn.disabled=false;alert(e.message)}});}catch(e){box.textContent=e.message;}}

async function gpAction(action,data={}){try{const j=await platformCall(action,{code:gameParty.code,...data});if(j.party)gameParty=j.party;renderGameParty()}catch(e){alert(e.message)}}
async function leaveGameParty(){if(!gameParty)return;const c=gameParty.code;gameParty=null;clearInterval(gamePartyTimer);try{await platformCall('game-party-leave',{code:c})}catch{};renderGameParty();}
function startGameParty(){clearInterval(gamePartyTimer);gamePartyTimer=setInterval(async()=>{if(!gameParty)return;try{const j=await platformCall('game-party-state',{code:gameParty.code});gameParty=j.party;const seq=gameParty.launch?.seq||0;if(seq>lastGamePartyLaunch){lastGamePartyLaunch=seq;const g=(window.BUILT_IN_GAMES||[]).find(x=>x.file===gameParty.game.file);if(g){toast('Party leader launched '+g.title,'🎉');window.openGame?.(g);if(gameParty.roomCode)navigator.clipboard?.writeText(gameParty.roomCode).catch(()=>{});}}if(!$('#mhGamePartyModal')?.hidden)renderGameParty();}catch{clearInterval(gamePartyTimer);gameParty=null}},2500);}

// ---------- Live TV extras ----------
function enhanceLiveTv(){const tab=$('#tab-livetv');if(!tab||$('#mhLiveExtras'))return;const x=document.createElement('div');x.id='mhLiveExtras';x.className='mh-live-extras';x.innerHTML='<button id="mhTvNow">● Jump to Now</button><button id="mhTvRecent">↻ Recent Channels</button><button id="mhTvTonight">☾ Tonight</button><button id="mhTvReminders">🔔 Reminders</button>';tab.prepend(x);$('#mhTvNow').onclick=()=>{const p=$('.live-guide-row.playing');p?.scrollIntoView({behavior:'smooth',block:'center'})};$('#mhTvRecent').onclick=showRecentTv;$('#mhTvTonight').onclick=showTonight;$('#mhTvReminders').onclick=showReminders;}
function showTvMini(title,html){let m=$('#mhTvMiniPanel');if(!m){m=document.createElement('section');m.id='mhTvMiniPanel';m.className='mh-platform-modal';m.hidden=true;m.innerHTML='<div class="mh-standard-card"><button class="mh-modal-x">×</button><h2 id="mhTvMiniTitle"></h2><div id="mhTvMiniBody"></div></div>';document.body.appendChild(m);m.querySelector('.mh-modal-x').onclick=()=>m.hidden=true;}$('#mhTvMiniTitle').textContent=title;$('#mhTvMiniBody').innerHTML=html;m.hidden=false;}
function tvHistory(){return read(key('platform_tv_history_v1'),[])}
function showRecentTv(){const h=tvHistory(),channels=window.mhGetLiveTvState?.()?.channels||[];showTvMini('Recent Channels',h.length?h.map(x=>`<button class="mh-tv-list" data-u="${esc(x.url)}"><span>📺</span><div><strong>${esc(x.name)}</strong><small>${esc(x.group||'Live TV')}</small></div></button>`).join(''):'<div class="mh-empty">No recent channels yet.</div>');$('#mhTvMiniBody').querySelectorAll('[data-u]').forEach(b=>b.onclick=()=>{const c=channels.find(x=>x.url===b.dataset.u);if(c){$('#mhTvMiniPanel').hidden=true;window.mhPlayIptvChannel?.(c)}});}
function showTonight(){const s=window.mhGetLiveTvState?.();if(!s)return showTvMini('Tonight','<div class="mh-empty">Open Live TV first to load guide data.</div>');const now=new Date(),start=new Date(now);start.setHours(17,0,0,0);const end=new Date(now);end.setHours(23,59,59,999);const rows=[];for(const c of s.channels||[]){const ps=s.epg?.[(c.tvgId||'').toLowerCase()]||s.epg?.[(c.name||'').toLowerCase()]||[];for(const p of ps){if(p.start>=start.getTime()&&p.start<=end.getTime())rows.push({c,p});}}rows.sort((a,b)=>a.p.start-b.p.start);showTvMini('Tonight',rows.length?rows.slice(0,80).map((x,i)=>`<button class="mh-tv-list" data-i="${i}"><span>${new Date(x.p.start).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}</span><div><strong>${esc(x.p.title)}</strong><small>${esc(x.c.name)}</small></div></button>`).join(''):'<div class="mh-empty">No EPG programs loaded for tonight yet.</div>');$('#mhTvMiniBody').querySelectorAll('[data-i]').forEach(b=>b.onclick=()=>{const x=rows[Number(b.dataset.i)];addTvReminder(x.c,x.p)});}
function reminders(){return read(key('platform_tv_reminders_v1'),[])}
function addTvReminder(c,p){const a=reminders().filter(x=>!(x.channel===c.name&&x.start===p.start));a.push({channel:c.name,title:p.title,start:p.start});write(key('platform_tv_reminders_v1'),a.slice(-40));toast('TV reminder saved','🔔');}
function showReminders(){const a=reminders().filter(x=>x.start>Date.now()-3600000);showTvMini('TV Reminders',a.length?a.sort((x,y)=>x.start-y.start).map(x=>`<div class="mh-tv-list static"><span>🔔</span><div><strong>${esc(x.title)}</strong><small>${esc(x.channel)} · ${new Date(x.start).toLocaleString()}</small></div></div>`).join(''):'<div class="mh-empty">No reminders yet. Open Tonight and tap a program.</div>');}
function checkTvReminders(){const now=Date.now(),a=reminders();for(const x of a){const id=`tvrem:${x.channel}:${x.start}`;if(x.start-now>0&&x.start-now<60000&&!sessionStorage.getItem(id)){sessionStorage.setItem(id,'1');toast(`${x.title} is starting on ${x.channel}`,'📺')}}}
function recordTv(c){const h=tvHistory().filter(x=>x.url!==c.url);h.unshift({name:c.name,url:c.url,group:c.group,at:Date.now()});write(key('platform_tv_history_v1'),h.slice(0,20));awardXP(3,'Watched Live TV',`tv:${c.url}`);const d=read(key('platform_tv_count_v1'),0)+1;write(key('platform_tv_count_v1'),d);if(d>=10)unlockAch('tv');platformCall('event',{type:'tv_channel',channel:c.name}).catch(()=>{});}
function patchLiveTv(){if(typeof window.mhPlayIptvChannel==='function'&&!window.mhPlayIptvChannel.__platform69){const base=window.mhPlayIptvChannel;const w=function(c,...a){recordTv(c);return base.call(this,c,...a)};w.__platform69=true;window.mhPlayIptvChannel=w;}}

// ---------- Persistent music player ----------
function persistMusicPlayer(){const bar=$('#spotifyPlayerBar');if(!bar||bar.parentElement===document.body)return;document.body.appendChild(bar);bar.classList.add('mh-global-music-player');const sync=()=>bar.classList.toggle('mh-has-track',!/^nothing playing$/i.test($('#musicNowPlaying')?.textContent?.trim()||''));new MutationObserver(sync).observe($('#musicNowPlaying')||bar,{childList:true,subtree:true,characterData:true});sync();}

// ---------- Chromebook dock, shortcuts, arcade mode ----------

function setArcadeMode(on){document.body.classList.toggle('mh-arcade-mode',on);localStorage.setItem(key('arcade_mode_v1'),on?'1':'0');toast(on?'Arcade Mode on':'Arcade Mode off','🎮');}
function shortcuts(e){
  if((e.ctrlKey||e.metaKey)&&String(e.key).toLowerCase()==='k'){e.preventDefault();e.stopImmediatePropagation();openSearch();return;}
  if(e.target&&/input|textarea|select/i.test(e.target.tagName))return;
  if(e.key==='/'){e.preventDefault();openSearch();return;}
  if(e.key==='Escape'){['#mhPlatformSearch','#mhNotifyPanel','#mhGameDetail','#mhStatsModal','#mhThemeStore','#mhGamePartyModal','#mhAdminModal','#mhTvMiniPanel'].forEach(s=>{const x=$(s);if(x&&!x.hidden)x.hidden=true});return;}
  const k=String(e.key).toLowerCase();
  if(document.body.dataset.hubTab==='livetv'&&/^[1-9]$/.test(k)){const rows=[...document.querySelectorAll('.live-guide-row')].filter(x=>x.offsetParent!==null);const row=rows[Number(k)-1];if(row){e.preventDefault();row.click();toast('Channel '+k,'📺');return;}}
  if(k==='f'){e.preventDefault();window.mhSocialOpen?.();return;}
  const tabs={g:'arcade',m:'movies',t:'livetv',s:'sports'};if(tabs[k]){e.preventDefault();window.switchTab?.(tabs[k],document.querySelector(`[data-tab="${tabs[k]}"]`));}
}

// ---------- Admin ----------
async function openAdmin(){
  if(!signedIn())return toast('Admin sign-in required','⚠');
  let status;try{status=await platformCall('admin-status')}catch{return toast('Admin check failed','⚠')}
  if(!status.isAdmin)return toast(status.configured?`Signed in as @${status.username||'account'} · admin username does not match`:`Set MEDIAHUB_ADMIN_USERNAME to ${status.username||'your Nova username'} in Vercel`,'🔒');
  let m=$('#mhAdminModal');if(!m){m=document.createElement('section');m.id='mhAdminModal';m.className='mh-platform-modal';m.hidden=true;m.innerHTML='<div class="mh-standard-card mh-admin-card"><button class="mh-modal-x">×</button><div id="mhAdminBody">Loading…</div></div>';document.body.appendChild(m);m.querySelector('.mh-modal-x').onclick=()=>m.hidden=true;}m.hidden=false;
  try{
    const j=await platformCall('admin-summary'),counts=j.counts||{};
    $('#mhAdminBody').innerHTML=`<small>PRIVATE</small><h2>Admin Dashboard</h2><p>Live site activity, accounts, Snack Drop, reports, and announcements.</p>
    <div class="mh-admin-metrics"><div><b>${counts.users??j.totalUsers??0}</b><span>Accounts</span></div><div><b>${counts.active??j.activeUsers??0}</b><span>Online now</span></div><div><b>${counts.orders??0}</b><span>Snack orders</span></div><div><b>${counts.reports??0}</b><span>Reports</span></div></div>
    <div class="mh-admin-grid"><section><h3>Most Played Games</h3>${(j.topGames||[]).slice(0,10).map((g,i)=>`<div class="mh-admin-row"><strong>${i+1}. ${esc(g.title||g.file)}</strong><small>${g.count||0} launch${g.count===1?'':'es'}</small></div>`).join('')||'<div class="mh-empty">No game analytics yet.</div>'}</section><section><h3>Recent Accounts</h3>${(j.users||[]).slice(0,10).map(u=>`<div class="mh-admin-row"><strong>@${esc(u.username)}</strong><small>${esc(u.displayName||u.username)} · ${u.createdAt?new Date(u.createdAt).toLocaleDateString():'Unknown date'}</small></div>`).join('')||'<div class="mh-empty">No accounts yet.</div>'}</section></div>
    <div class="mh-admin-grid"><section><h3>Recent Snack Orders</h3>${(j.orders||[]).slice(0,12).map(o=>`<div class="mh-admin-row"><strong>${esc(o.name)} · $${Number(o.estimated_total||0).toFixed(2)}</strong><small>${esc(o.date)} · ${esc(o.delivery_window)} · ${esc(o.meeting_spot)}</small><p>${esc(o.order_items)}</p></div>`).join('')||'<div class="mh-empty">No orders.</div>'}</section><section><h3>Issue Reports</h3>${(j.reports||[]).slice(0,16).map(r=>`<div class="mh-admin-row"><strong>${esc(r.subject||r.name||'Report')}</strong><small>${esc(r.category||r.kind||'Issue')} · ${new Date(r.at).toLocaleString()}${r.username?' · @'+esc(r.username):''}</small>${r.details?`<p>${esc(r.details)}</p>`:''}</div>`).join('')||'<div class="mh-empty">No reports.</div>'}</section></div>
    <section><h3>Announcements</h3><div class="mh-admin-compose"><input id="mhAdminAnnTitle" maxlength="80" placeholder="Announcement title"><textarea id="mhAdminAnnBody" maxlength="280" placeholder="What changed?"></textarea><button id="mhAdminPost">Publish announcement</button></div>${(j.announcements||[]).slice(0,6).map(a=>`<div class="mh-admin-row"><strong>${esc(a.title)}</strong><small>${a.at?new Date(a.at).toLocaleString():''}</small><p>${esc(a.body||'')}</p></div>`).join('')}</section>`;
    $('#mhAdminPost').onclick=async()=>{const title=$('#mhAdminAnnTitle').value.trim(),body=$('#mhAdminAnnBody').value.trim();if(!title)return;const old=j.announcements||[];await platformCall('admin-announcements',{items:[{id:String(Date.now()),title,body,at:Date.now()},...old].slice(0,12)});toast('Announcement published','📣');refreshNotifications();openAdmin();};
  }catch(e){$('#mhAdminBody').textContent=e.message}
}

// ---------- Update modal ----------
function showWhatsNew(){const seen=localStorage.getItem('mh_seen_build_nova_v132');if(seen===BUILD)return;let m=document.createElement('section');m.className='mh-update-modal';m.innerHTML='<div><small>NOVA MATH v1.3.2</small><h2>What’s New</h2><p>Nova Math v1.3.2 adds easier admin access, private Discord issue alerts, stronger Movies & TV embeds, clearer SteamGridDB checks, and refreshed Nova branding.</p><div class="mh-update-list"><span>🛠 Easier Admin Dashboard</span><span>📨 Private Issue Reports</span><span>🔔 Discord Admin Alerts</span><span>🎮 SteamGridDB Diagnostics</span><span>🎬 Movies & TV Embed Fix</span><span>✦ Nova Header Refresh</span><span>🤖 UnoRouter Fallback Models</span><span>💾 Redis Accounts & Social</span></div><button id="mhUpdateDone">Close</button></div>';document.body.appendChild(m);$('#mhUpdateDone').onclick=()=>{localStorage.setItem('mh_seen_build_nova_v132',BUILD);m.remove()};}

// ---------- Settings upgrades ----------
function injectSettings(){const s=$('#mhSettings');if(!s||$('#mhPlatformSettings'))return;const host=$('#mhSettingsBody')||s.querySelector('.mh-settings-grid')||s;const box=document.createElement('section');box.id='mhPlatformSettings';box.className='mh-platform-settings';box.innerHTML='<h3>Nova Math Platform</h3><div><button onclick="mhOpenStats()">📊 Stats & Achievements</button><button onclick="mhOpenThemeStore()">🎨 Theme Store</button><button onclick="mhOpenGameParty()">🎉 Game Party</button><button onclick="mhOpenNotifications()">🔔 Notifications</button><button onclick="mhToggleArcadeMode()">🎛 Arcade Mode</button><button onclick="mhOpenAdmin()">🛠 Admin Dashboard</button></div><p>Keyboard: G Games · M Movies · T TV · S Sports · F Friends · / Search · Esc Close</p>';host.appendChild(box);}


async function syncAdminHeader(){
 const tools=document.querySelector('.hub-tools');if(!tools)return;let b=$('#mhAdminHeaderBtn');
 if(!signedIn()){b?.remove();return;}
 try{const s=await platformCall('admin-status');if(!s.isAdmin){b?.remove();return;}if(!b){b=document.createElement('button');b.id='mhAdminHeaderBtn';b.className='hub-admin-btn';b.type='button';b.innerHTML='<span>◇</span><span>Admin</span>';b.onclick=openAdmin;const settings=$('#mhSettingsBtn');tools.insertBefore(b,settings||tools.firstChild);}}catch{b?.remove();}
}

// ---------- Core patching ----------
function patchMovies(){if(typeof window.openMoviePlayer==='function'&&!window.openMoviePlayer.__platform69){const base=window.openMoviePlayer;const w=async function(...args){awardXP(5,'Started a title',`movie:${args[0]}:${args[1]}`);const n=read(key('platform_movie_count_v1'),0)+1;write(key('platform_movie_count_v1'),n);if(n>=3)unlockAch('movie');platformCall('event',{type:'movie_play',movie:String(args[2]||args[1]||'')}).catch(()=>{});return base.apply(this,args)};w.__platform69=true;window.openMoviePlayer=w;}}
function patchQuickLaunch(){window.openPlatformSearch=openSearch;window.openQuickLaunch=openSearch;}
function reportBrokenHook(){const b=$('#iptvReportBroken');if(!b||b.dataset.platform69==='1')return;b.dataset.platform69='1';b.addEventListener('click',()=>{const c=window.mhGetLiveTvState?.()?.current;if(c)platformCall('report-channel',{name:c.name,url:c.url,tvgId:c.tvgId||'',group:c.group||''}).catch(()=>{});},{capture:true});}
function patchCore(){patchGames();patchMovies();patchLiveTv();patchSecrets();patchQuickLaunch();reportBrokenHook();}
function init(){dailyXP();applyPlatformTheme();ensureNotifications();ensureSearch();interceptGameCards();renderHomeUpgrade();enhanceLiveTv();persistMusicPlayer();injectSettings();patchCore();syncAdminHeader();evaluateAchievements();if(localStorage.getItem(key('arcade_mode_v1'))==='1')document.body.classList.add('mh-arcade-mode');setTimeout(()=>{patchCore();renderHomeUpgrade();reportBrokenHook();syncAdminHeader()},1200);setTimeout(showWhatsNew,1800);notifyTimer=setInterval(()=>{refreshNotifications();checkTvReminders();reportBrokenHook()},30000);refreshNotifications();document.addEventListener('keydown',shortcuts,true);new MutationObserver(()=>{if(document.body.dataset.hubTab==='arcade')renderHomeUpgrade();if(document.body.dataset.hubTab==='livetv'){enhanceLiveTv();reportBrokenHook()}injectSettings();}).observe(document.body,{attributes:true,attributeFilter:['data-hub-tab'],childList:true,subtree:false});}
window.mhOpenNotifications=openNotifications;window.mhOpenStats=openStats;window.mhOpenThemeStore=openThemeStore;window.mhOpenGameDetails=openGameDetails;window.mhOpenGameParty=openGameParty;window.mhOpenAdmin=openAdmin;window.mhToggleArcadeMode=()=>setArcadeMode(!document.body.classList.contains('mh-arcade-mode'));window.mhPlatformSearch=openSearch;window.mhAwardXP=awardXP;
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
