(()=>{
'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const profile=()=>localStorage.getItem('mh_active_profile_v1')||'default';
const key=k=>`mh:${profile()}:${k}`;
const read=(k,d)=>{try{const x=JSON.parse(localStorage.getItem(k));return x==null?d:x}catch{return d}};
const write=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v));window.mhScheduleCloudSync?.()}catch{}};
const LEAGUES=[['nfl','NFL'],['nba','NBA'],['mlb','MLB'],['nhl','NHL'],['ncaaf','NCAAF'],['ncaam','NCAAM'],['wnba','WNBA'],['mls','MLS']];
const ESPN_LEAGUES={nfl:['football','nfl','NFL'],nba:['basketball','nba','NBA'],mlb:['baseball','mlb','MLB'],nhl:['hockey','nhl','NHL'],ncaaf:['football','college-football','NCAAF'],ncaam:['basketball','mens-college-basketball','NCAAM'],wnba:['basketball','wnba','WNBA'],mls:['soccer','usa.1','MLS']};
let activeLeague='nfl',scoreTimer=null,channels=[],channelFilter='',channelHls=null,currentChannel=null,lastScores=[],mounted=false,gameModal=null,redZoneChannel=null,channelSource='';
const ymd=d=>`${d.getFullYear()}${String(d.getMonth()+1).padStart(2,'0')}${String(d.getDate()).padStart(2,'0')}`;
function directEventRow(e={}){const c=e.competitions?.[0]||{},st=c.status||e.status||{},type=st.type||{},teams=(c.competitors||[]).map(x=>({id:String(x.id||x.team?.id||''),homeAway:String(x.homeAway||''),score:String(x.score??''),winner:!!x.winner,name:String(x.team?.displayName||x.team?.shortDisplayName||x.team?.name||''),shortName:String(x.team?.shortDisplayName||x.team?.name||''),abbreviation:String(x.team?.abbreviation||''),logo:String(x.team?.logo||''),record:String((x.records||[])[0]?.summary||'')}));return{id:String(e.id||''),name:String(e.name||''),shortName:String(e.shortName||''),date:e.date||c.date||'',status:{state:String(type.state||''),name:String(type.name||''),detail:String(type.shortDetail||type.detail||type.description||''),clock:String(st.displayClock||''),period:Number(st.period||0),completed:!!type.completed},teams,broadcasts:(c.broadcasts||[]).flatMap(x=>x.names||[]),venue:String(c.venue?.fullName||''),source:'ESPN direct fallback'};}
async function directScoreboard(league){const cfg=ESPN_LEAGUES[league]||ESPN_LEAGUES.nfl,now=new Date(),start=new Date(now.getTime()-2*86400000),end=new Date(now.getTime()+8*86400000),url=new URL(`https://site.api.espn.com/apis/site/v2/sports/${cfg[0]}/${cfg[1]}/scoreboard`);url.searchParams.set('dates',`${ymd(start)}-${ymd(end)}`);url.searchParams.set('limit',(league==='ncaaf'||league==='ncaam')?'250':'100');const r=await fetch(url.toString(),{cache:'no-store'});if(!r.ok)throw new Error('Sports backend unavailable');const raw=await r.json();return{league,label:cfg[2],events:(raw.events||[]).map(directEventRow).sort((a,b)=>new Date(a.date||0)-new Date(b.date||0)),updatedAt:Date.now(),source:'ESPN direct fallback'};}
const api=async(params)=>{const q=new URLSearchParams(params);try{const r=await fetch('/api/sports-api?'+q.toString(),{cache:'no-store'});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'Sports backend unavailable');return j;}catch(e){if((params.action||'scoreboard')==='scoreboard')return directScoreboard(params.league||'nfl');throw e;}};
const fmtTime=d=>{const x=new Date(d);return Number.isNaN(x.getTime())?'':x.toLocaleString([], {weekday:'short',hour:'numeric',minute:'2-digit'});};
const favTeams=()=>new Set(read(key('sports_fav_teams_v1'),[]));
const favChannels=()=>new Set(read(key('sports_fav_channels_v1'),[]));
function toast(t,i='🏟️'){window.showToast?.(t,i)}
function mount(){
  const root=$('#sportsMount');if(!root)return;
  if(!mounted){mounted=true;root.innerHTML=`
  <section class="mh-sports-page">
    <div class="mh-sports-hero">
      <div><small>LIVE SPORTS</small><h2>Sports Center</h2><p>Live scores, sports channels from configured public sources, schedules, NFL fantasy estimates, and a RedZone live tracker.</p></div>
      <div class="mh-sports-live-pill"><span></span><strong id="mhSportsLiveCount">0</strong><small>LIVE NOW</small></div>
    </div>
    <div class="mh-sports-leagues" id="mhSportsLeagues"></div>
    <div class="mh-sports-layout">
      <main>
        <section class="mh-sports-card mh-redzone-card" id="mhRedZoneCard">
          <div class="mh-sports-card-head"><div><small>NFL LIVE</small><h3>RedZone + Live Tracker</h3></div><div class="mh-redzone-actions"><button id="mhRedZoneWatch" disabled>Finding RedZone…</button><button id="mhRedZoneRefresh">Refresh</button></div></div>
          <p id="mhRedZoneSource" class="mh-sports-sub">Checking configured public sports sources for a RedZone channel while tracking live NFL games below.</p>
          <div id="mhRedZoneGames" class="mh-redzone-games"><div class="mh-sports-loading">Loading NFL games…</div></div>
        </section>
        <section class="mh-sports-card">
          <div class="mh-sports-card-head"><div><small id="mhSportsLeagueKicker">NFL</small><h3>Scores & Schedule</h3></div><span id="mhSportsUpdated">Updating…</span></div>
          <div id="mhSportsScores" class="mh-score-grid"><div class="mh-sports-loading">Loading scores…</div></div>
        </section>
      </main>
      <aside>
        <section class="mh-sports-card mh-sports-player-card">
          <div class="mh-sports-card-head"><div><small>PUBLIC SPORTS TV</small><h3 id="mhSportsNowTitle">Sports Channels</h3></div><button id="mhSportsPip" title="Picture in Picture">PiP</button></div>
          <div class="mh-sports-video-shell"><video id="mhSportsVideo" controls playsinline webkit-playsinline></video><div id="mhSportsVideoEmpty"><span>▶</span><strong>Pick a channel</strong><small>Only public playlist sources are loaded here.</small></div></div>
          <div class="mh-sports-player-actions"><button id="mhSportsFullscreen">Fullscreen</button><button id="mhSportsStop">Stop</button></div>
          <div id="mhSportsPlayerStatus" class="mh-sports-status">Loading IPTV-org and IPTV Cat sports channels…</div>
        </section>
      </aside>
    </div>
    <section class="mh-sports-card mh-sports-channels-card">
      <div class="mh-sports-card-head"><div><small>SPORTS CHANNELS</small><h3>Watch</h3></div><div class="mh-sports-channel-tools"><input id="mhSportsChannelSearch" type="search" placeholder="Search channels"><button id="mhSportsFavOnly">★ Favorites</button></div></div>
      <div id="mhSportsChannels" class="mh-sports-channels"><div class="mh-sports-loading">Loading public sports playlist…</div></div>
    </section>
  </section>`;
    renderLeagues();
    $('#mhSportsChannelSearch').addEventListener('input',e=>{channelFilter=e.target.value.trim().toLowerCase();renderChannels();});
    $('#mhSportsFavOnly').onclick=()=>{const b=$('#mhSportsFavOnly');b.classList.toggle('active');renderChannels();};
    $('#mhSportsFullscreen').onclick=fullscreen;$('#mhSportsPip').onclick=pip;$('#mhSportsStop').onclick=stopChannel;$('#mhRedZoneRefresh').onclick=()=>{loadRedZone(true);loadChannels(true)};$('#mhRedZoneWatch').onclick=()=>{if(redZoneChannel){playChannel(redZoneChannel);document.querySelector('.mh-sports-player-card')?.scrollIntoView({behavior:'smooth',block:'center'});}};
    loadChannels();
  }
  loadScores();loadRedZone();startRefresh();
}
function renderLeagues(){const host=$('#mhSportsLeagues');if(!host)return;host.innerHTML=LEAGUES.map(([id,label])=>`<button data-league="${id}" class="${id===activeLeague?'active':''}">${label}</button>`).join('');host.querySelectorAll('[data-league]').forEach(b=>b.onclick=()=>{activeLeague=b.dataset.league;renderLeagues();loadScores(true);});}
async function loadScores(showLoading=false){const host=$('#mhSportsScores');if(!host)return;if(showLoading)host.innerHTML='<div class="mh-sports-loading">Updating scores…</div>';try{const j=await api({action:'scoreboard',league:activeLeague});lastScores=j.events||[];renderScores(lastScores);const live=lastScores.filter(e=>e.status?.state==='in').length;$('#mhSportsLiveCount').textContent=String(live);$('#mhSportsLeagueKicker').textContent=j.label||activeLeague.toUpperCase();$('#mhSportsUpdated').textContent='Updated '+new Date(j.updatedAt||Date.now()).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})+' · Live scores';}catch(e){host.innerHTML=`<div class="mh-sports-error">${esc(e.message)} <button onclick="window.mhSportsRefresh?.()">Retry</button></div>`;}}
function renderScores(events){const host=$('#mhSportsScores');if(!host)return;if(!events.length){host.innerHTML='<div class="mh-sports-empty">No games found for this league right now.</div>';return;}const fav=favTeams();host.innerHTML=events.map(e=>{const away=e.teams?.find(t=>t.homeAway==='away')||e.teams?.[0]||{},home=e.teams?.find(t=>t.homeAway==='home')||e.teams?.[1]||{};const live=e.status?.state==='in',pre=e.status?.state==='pre';const star=fav.has(away.id)||fav.has(home.id);return `<article class="mh-score-card ${live?'live':''}" data-game="${esc(e.id)}"><div class="mh-score-top"><span>${live?'<i></i> LIVE':pre?fmtTime(e.date):esc(e.status?.detail||'Final')}</span><small>${esc((e.broadcasts||[]).join(' · '))}</small><button data-fav-game="${esc(e.id)}" title="Favorite teams">${star?'★':'☆'}</button></div>${teamLine(away)}${teamLine(home)}<div class="mh-score-foot"><span>${esc(e.venue||'')}</span><button data-detail="${esc(e.id)}">Game Center</button></div></article>`;}).join('');host.querySelectorAll('[data-detail]').forEach(b=>b.onclick=e=>{e.stopPropagation();openGame(b.dataset.detail)});host.querySelectorAll('[data-fav-game]').forEach(b=>b.onclick=e=>{e.stopPropagation();const ev=events.find(x=>x.id===b.dataset.favGame);if(ev)toggleGameTeams(ev);});}
function teamLine(t){return `<div class="mh-score-team"><span class="mh-score-logo">${t.logo?`<img src="${esc(t.logo)}" alt="">`:esc(t.abbreviation||'?')}</span><div><strong>${esc(t.shortName||t.name||'Team')}</strong><small>${esc(t.record||t.abbreviation||'')}</small></div><b>${esc(t.score||'')}</b></div>`;}
function toggleGameTeams(e){const set=favTeams(),ids=(e.teams||[]).map(t=>t.id).filter(Boolean),all=ids.every(id=>set.has(id));ids.forEach(id=>all?set.delete(id):set.add(id));write(key('sports_fav_teams_v1'),[...set]);renderScores(lastScores);toast(all?'Teams removed from favorites':'Teams favorited',all?'☆':'★');}
async function loadRedZone(force=false){const host=$('#mhRedZoneGames');if(!host)return;if(force)host.innerHTML='<div class="mh-sports-loading">Refreshing NFL tracker…</div>';try{const j=await api({action:'scoreboard',league:'nfl'}),events=j.events||[],live=events.filter(e=>e.status?.state==='in');host.innerHTML=(live.length?live:events.filter(e=>e.status?.state==='pre').slice(0,6)).map(e=>{const a=e.teams?.find(t=>t.homeAway==='away')||{},h=e.teams?.find(t=>t.homeAway==='home')||{};return `<button class="mh-redzone-game ${e.status?.state==='in'?'live':''}" data-rz="${esc(e.id)}"><span>${e.status?.state==='in'?'LIVE':fmtTime(e.date)}</span><div><b>${esc(a.abbreviation||a.shortName)} ${esc(a.score||'')}</b><b>${esc(h.abbreviation||h.shortName)} ${esc(h.score||'')}</b></div><small>${esc(e.status?.detail||'')}</small></button>`;}).join('')||'<div class="mh-sports-empty">No NFL games scheduled right now.</div>';host.querySelectorAll('[data-rz]').forEach(b=>b.onclick=()=>openGame(b.dataset.rz,'nfl'));}catch(e){host.innerHTML='<div class="mh-sports-error">NFL tracker unavailable.</div>';}}
function ensureGameModal(){if(gameModal)return gameModal;gameModal=document.createElement('section');gameModal.id='mhSportsGameModal';gameModal.className='mh-sports-modal';gameModal.hidden=true;gameModal.innerHTML='<div class="mh-sports-modal-card"><button id="mhSportsGameClose" class="mh-sports-modal-close">×</button><div id="mhSportsGameBody"></div></div>';document.body.appendChild(gameModal);$('#mhSportsGameClose').onclick=()=>gameModal.hidden=true;gameModal.addEventListener('click',e=>{if(e.target===gameModal)gameModal.hidden=true});return gameModal;}
async function openGame(id,league=activeLeague){const m=ensureGameModal(),body=$('#mhSportsGameBody');m.hidden=false;body.innerHTML='<div class="mh-sports-loading">Loading Game Center…</div>';try{const j=await api({action:'game',league,id}),d=j.details||{};const a=d.teams?.find(t=>t.homeAway==='away')||d.teams?.[0]||{},h=d.teams?.find(t=>t.homeAway==='home')||d.teams?.[1]||{};body.innerHTML=`<div class="mh-gamecenter-head"><small>${league.toUpperCase()} GAME CENTER</small><h2>${esc(a.shortName||a.name)} ${esc(a.score||'')} <span>at</span> ${esc(h.shortName||h.name)} ${esc(h.score||'')}</h2><p>${esc(d.status?.detail||'')}</p></div>${d.fantasy?.length?fantasyTable(d.fantasy,d.fantasyScoring):''}<section class="mh-gamecenter-section"><h3>Scoring</h3>${d.scoring?.length?d.scoring.slice().reverse().map(x=>`<div class="mh-scoring-row"><span>Q${x.period} ${esc(x.clock)}</span><strong>${esc(x.text)}</strong><b>${x.awayScore}-${x.homeScore}</b></div>`).join(''):'<div class="mh-sports-empty">No scoring plays available.</div>'}</section>`;}catch(e){body.innerHTML=`<div class="mh-sports-error">${esc(e.message)}</div>`;}}
function fantasyTable(rows,note){return `<section class="mh-gamecenter-section"><div class="mh-fantasy-head"><div><h3>Fantasy Points</h3><p>Average of Standard, Half-PPR, and PPR estimates.</p></div><span>LIVE ESTIMATE</span></div><div class="mh-fantasy-table"><div class="mh-fantasy-row head"><span>Player</span><b>AVG</b><b>STD</b><b>0.5</b><b>PPR</b></div>${rows.slice(0,18).map(p=>`<div class="mh-fantasy-row"><span>${p.headshot?`<img src="${esc(p.headshot)}" alt="">`:''}<em><strong>${esc(p.name)}</strong><small>${esc(p.team)} ${esc(p.position)}</small></em></span><b>${p.average.toFixed(1)}</b><b>${p.standard.toFixed(1)}</b><b>${p.half.toFixed(1)}</b><b>${p.ppr.toFixed(1)}</b></div>`).join('')}</div><small class="mh-fantasy-note">${esc(note||'')}</small></section>`;}
async function loadChannels(force=false){const host=$('#mhSportsChannels');if(!host)return;try{const j=await api({action:'channels',...(force?{t:Date.now()}: {})});channels=j.channels||[];redZoneChannel=j.redZone||channels.find(c=>/red\s*zone|redzone/i.test(`${c.name} ${c.group||''}`))||null;channelSource=j.source||'';updateRedZoneSource();renderChannels();}catch(e){redZoneChannel=null;updateRedZoneSource(e.message);host.innerHTML=`<div class="mh-sports-error">${esc(e.message)}</div>`;}}

function sourceLabel(c){
  if(c?.source==='botasaurus-public-page')return 'Botasaurus';
  if(c?.source==='iptvcat-my-list')return 'IPTV Cat';
  if(c?.source==='iptv-org-sports')return 'IPTV-org';
  return 'Public source';
}
function updateRedZoneSource(error=''){
  const btn=$('#mhRedZoneWatch'),note=$('#mhRedZoneSource');
  if(btn){btn.disabled=!redZoneChannel;btn.textContent=redZoneChannel?'▶ Watch RedZone':'RedZone unavailable';btn.classList.toggle('available',!!redZoneChannel);}
  if(note){if(redZoneChannel)note.textContent=`${redZoneChannel.name} found via ${sourceLabel(redZoneChannel)}. Select Watch RedZone to open it in the Sports player.`;else if(error)note.textContent=`Could not check the configured RedZone sources right now. ${error}`;else note.textContent='Configured public sports sources loaded, but no RedZone entry is available right now. Live NFL scores still update below.';}
}
function renderChannels(){const host=$('#mhSportsChannels');if(!host)return;const fav=favChannels(),only=$('#mhSportsFavOnly')?.classList.contains('active');let rows=channels.filter(c=>(!channelFilter||`${c.name} ${c.group||''} ${c.country||''}`.toLowerCase().includes(channelFilter))&&(!only||fav.has(c.url)));rows.sort((a,b)=>Number(fav.has(b.url))-Number(fav.has(a.url))||String(a.name).localeCompare(String(b.name)));host.innerHTML=rows.slice(0,180).map((c,i)=>`<article class="mh-sports-channel"><button class="mh-sports-channel-main" data-channel="${i}">${c.logo?`<img src="${esc(c.logo)}" alt="">`:'<span>TV</span>'}<div><strong>${esc(c.name)}</strong><small>${esc([c.group||c.country||'Sports',sourceLabel(c)].filter(Boolean).join(' · '))}</small></div><i>▶</i></button><button class="mh-sports-star ${fav.has(c.url)?'active':''}" data-star="${i}">${fav.has(c.url)?'★':'☆'}</button></article>`).join('')||'<div class="mh-sports-empty">No matching channels.</div>';host.querySelectorAll('[data-channel]').forEach(b=>b.onclick=()=>playChannel(rows[Number(b.dataset.channel)]));host.querySelectorAll('[data-star]').forEach(b=>b.onclick=()=>toggleChannel(rows[Number(b.dataset.star)]));}
function toggleChannel(c){if(!c)return;const set=favChannels();if(set.has(c.url))set.delete(c.url);else set.add(c.url);write(key('sports_fav_channels_v1'),[...set]);renderChannels();}
function stopChannel(){try{channelHls?.destroy()}catch{}channelHls=null;const v=$('#mhSportsVideo');if(v){try{v.pause();v.removeAttribute('src');v.load()}catch{}}currentChannel=null;$('#mhSportsVideoEmpty').hidden=false;$('#mhSportsNowTitle').textContent='Sports Channels';$('#mhSportsPlayerStatus').textContent='Playback stopped.';}
function playChannel(c){if(!c?.url)return;stopChannel();currentChannel=c;const v=$('#mhSportsVideo'),empty=$('#mhSportsVideoEmpty');if(!v)return;empty.hidden=true;$('#mhSportsNowTitle').textContent=c.name;$('#mhSportsPlayerStatus').textContent='Connecting to '+c.name+'…';const u=c.url,isHls=/\.m3u8(?:$|\?)/i.test(u)||/m3u8/i.test(u);try{if(isHls&&v.canPlayType('application/vnd.apple.mpegurl')){v.src=u;v.play().catch(()=>{});}else if(isHls&&window.Hls?.isSupported()){channelHls=new Hls({enableWorker:true,lowLatencyMode:true,maxBufferLength:20});channelHls.loadSource(u);channelHls.attachMedia(v);channelHls.on(Hls.Events.MANIFEST_PARSED,()=>v.play().catch(()=>{}));channelHls.on(Hls.Events.ERROR,(_,data)=>{if(data?.fatal)$('#mhSportsPlayerStatus').textContent='This public channel is not playing right now.';});}else{v.src=u;v.play().catch(()=>{});}$('#mhSportsPlayerStatus').textContent='Playing '+c.name+'. Availability depends on the broadcaster.';window.mhAwardXP?.(3,'Watched sports',`sports:${c.tvgId||c.name}`);}catch{$('#mhSportsPlayerStatus').textContent='Could not start this channel.';}}
async function fullscreen(){const shell=$('.mh-sports-video-shell'),v=$('#mhSportsVideo');try{if(document.fullscreenElement)return document.exitFullscreen();if(shell?.requestFullscreen)return shell.requestFullscreen();v?.webkitEnterFullscreen?.();}catch{}}
async function pip(){const v=$('#mhSportsVideo');try{if(document.pictureInPictureElement)return document.exitPictureInPicture();if(v?.requestPictureInPicture)return v.requestPictureInPicture();}catch{toast('Picture-in-Picture is unavailable','⚠')}}
function startRefresh(){clearInterval(scoreTimer);scoreTimer=setInterval(()=>{if(document.body.dataset.hubTab==='sports'){loadScores();loadRedZone();}},30000);}
function search(q){q=String(q||'').trim().toLowerCase();const out=[];if(!q)return out;for(const [id,label] of LEAGUES)if(label.toLowerCase().includes(q))out.push({icon:'🏟️',title:label+' Sports',subtitle:'Scores, schedules and live sports',run:()=>{activeLeague=id;window.switchTab?.('sports',document.querySelector('[data-tab="sports"]'));setTimeout(()=>{renderLeagues();loadScores(true)},120)}});for(const c of channels.filter(c=>`${c.name} ${c.group||''}`.toLowerCase().includes(q)).slice(0,5))out.push({icon:'📡',title:c.name,subtitle:c.group||'Sports channel',run:()=>{window.switchTab?.('sports',document.querySelector('[data-tab="sports"]'));setTimeout(()=>playChannel(c),180)}});return out.slice(0,8);}
window.mountSportsTab=mount;window.mhSportsRefresh=()=>loadScores(true);window.mhSportsSearch=search;window.mhSportsOpenGame=openGame;
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{if(document.body.dataset.hubTab==='sports')mount()});
})();
