const GUIDES_URL='https://iptv-org.github.io/api/guides.json';
const CACHE_MS=6*60*60*1000;
let guideCache={at:0,data:[]};
const xmlCache=new Map();
const headers={'Content-Type':'application/json; charset=utf-8','Cache-Control':'public, max-age=120, s-maxage=600, stale-while-revalidate=1800'};
function norm(v=''){return String(v).toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/\b(hd|fhd|uhd|4k|tv|channel|network)\b/g,'').replace(/[^a-z0-9]+/g,'').trim();}
function decodeXml(v=''){return String(v).replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,'$1').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&apos;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>');}
function parseTime(v=''){const m=String(v).match(/^(\d{4})(\d{2})(\d{2})(\d{2})(\d{2})(\d{2})?\s*([+-]\d{4}|Z)?/);if(!m)return NaN;const iso=`${m[1]}-${m[2]}-${m[3]}T${m[4]}:${m[5]}:${m[6]||'00'}${m[7]==='Z'?'Z':m[7]?m[7].slice(0,3)+':'+m[7].slice(3):'Z'}`;return Date.parse(iso);}
async function getGuides(){if(guideCache.data.length&&Date.now()-guideCache.at<CACHE_MS)return guideCache.data;const r=await fetch(GUIDES_URL,{headers:{'User-Agent':'MediaHub/1.0'}});if(!r.ok)throw new Error(`guide index HTTP ${r.status}`);const data=await r.json();guideCache={at:Date.now(),data:Array.isArray(data)?data:[]};return guideCache.data;}
async function getXml(url){const hit=xmlCache.get(url);if(hit&&Date.now()-hit.at<CACHE_MS)return hit.text;const ctrl=new AbortController(),timer=setTimeout(()=>ctrl.abort(),12000);try{const r=await fetch(url,{signal:ctrl.signal,headers:{'User-Agent':'MediaHub/1.0','Accept':'application/xml,text/xml,text/plain,*/*'}});if(!r.ok)throw new Error(`EPG HTTP ${r.status}`);const text=await r.text();if(text.length>25_000_000)throw new Error('EPG source too large');xmlCache.set(url,{at:Date.now(),text});return text;}finally{clearTimeout(timer);}}
function parsePrograms(xml,ids){const wanted=new Set(ids);const out={};const re=/<programme\b([^>]*)>([\s\S]*?)<\/programme>/gi;let m;while((m=re.exec(xml))){const a=m[1],body=m[2];const cm=a.match(/\bchannel="([^"]+)"/i);if(!cm||!wanted.has(cm[1]))continue;const sm=a.match(/\bstart="([^"]+)"/i),em=a.match(/\bstop="([^"]+)"/i);const tm=body.match(/<title(?:\s[^>]*)?>([\s\S]*?)<\/title>/i);const start=parseTime(sm?.[1]),stop=parseTime(em?.[1]);if(!Number.isFinite(start)||!Number.isFinite(stop)||stop<Date.now()-2*3600000||start>Date.now()+8*3600000)continue;(out[cm[1]]??=[]).push({title:decodeXml(tm?.[1]||'Program').replace(/<[^>]+>/g,'').trim(),start,stop});}for(const k of Object.keys(out))out[k].sort((a,b)=>a.start-b.start);return out;}
exports.handler=async event=>{if(event.httpMethod!=='POST')return{statusCode:405,headers,body:JSON.stringify({error:'POST required'})};try{const body=JSON.parse(event.body||'{}'),requested=(Array.isArray(body.channels)?body.channels:[]).slice(0,120).map(c=>({tvgId:String(c?.tvgId||'').trim(),name:String(c?.name||'').trim()})).filter(c=>c.tvgId||c.name);const guides=await getGuides();const byId=new Map(),byName=new Map();for(const g of guides){if(g.channel&&!byId.has(g.channel))byId.set(g.channel,g);const n=norm(g.site_name||g.channel||'');if(n&&!byName.has(n))byName.set(n,g);}const matches=[];for(const c of requested){let g=c.tvgId?byId.get(c.tvgId):null;if(!g&&c.name)g=byName.get(norm(c.name));if(g&&g.sources?.length)matches.push({request:c,guide:g,source:g.sources.find(s=>s.format==='XML')||g.sources[0]});}const sourceGroups=new Map();for(const m of matches){const url=m.source?.url;if(!/^https:\/\//i.test(url||''))continue;if(!sourceGroups.has(url))sourceGroups.set(url,[]);sourceGroups.get(url).push(m);}const programs={};let used=0;for(const [url,items] of [...sourceGroups.entries()].sort((a,b)=>b[1].length-a[1].length).slice(0,8)){try{const xml=await getXml(url),ids=[...new Set(items.map(x=>x.guide.channel).filter(Boolean))],parsed=parsePrograms(xml,ids);for(const item of items){const arr=parsed[item.guide.channel]||[];const key=(item.request.tvgId||item.request.name).toLowerCase();programs[key]=arr;if(arr.length)used++;}}catch(e){console.warn('EPG source failed',url,e.message);}}return{statusCode:200,headers,body:JSON.stringify({programs,matched:used,requested:requested.length,fetchedAt:new Date().toISOString()})};}catch(e){console.error('iptv-epg error',e);return{statusCode:502,headers:{...headers,'Cache-Control':'no-store'},body:JSON.stringify({error:'Could not load program guide data right now.'})};}};
