const crypto=require('crypto');
const headers={'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'};
const norm=s=>String(s||'').trim().toLowerCase();
const valid=u=>/^[a-z0-9_]{3,20}$/.test(u);
const secret=()=>process.env.MEDIAHUB_AUTH_SECRET||process.env.SOCIAL_AUTH_SECRET||'';
const b64=o=>Buffer.from(JSON.stringify(o)).toString('base64url');
function sign(payload){const s=secret();if(!s)throw new Error('MEDIAHUB_AUTH_SECRET is not configured');const p=b64(payload),sig=crypto.createHmac('sha256',s).update(p).digest('base64url');return `${p}.${sig}`;}
function hashPassword(password,salt=crypto.randomBytes(16).toString('hex')){const hash=crypto.scryptSync(password,salt,64).toString('hex');return {salt,hash};}
function verify(password,salt,expected){const got=crypto.scryptSync(password,salt,64);const exp=Buffer.from(expected,'hex');return got.length===exp.length&&crypto.timingSafeEqual(got,exp);}
exports.handler=async event=>{try{if(event.httpMethod==='GET'){if(!secret())return{statusCode:503,headers,body:JSON.stringify({ok:false,configured:false,error:'Account service is not configured.'})};const {getStore}=require('../vercel-store.cjs');const store=getStore('mediahub-social');await store.get('__health__',{consistency:'strong'});return{statusCode:200,headers,body:JSON.stringify({ok:true,configured:true})};}if(event.httpMethod!=='POST')return{statusCode:405,headers,body:JSON.stringify({error:'Method not allowed'})};if(!secret())return{statusCode:503,headers,body:JSON.stringify({error:'Account service is not configured.'})};const {getStore}=require('../vercel-store.cjs');const store=getStore('mediahub-social');const body=JSON.parse(event.body||'{}'),action=body.action,u=norm(body.username),password=String(body.password||'');if(!valid(u))return{statusCode:400,headers,body:JSON.stringify({error:'Username must be 3–20 characters using letters, numbers, or underscores.'})};if(password.length<6||password.length>128)return{statusCode:400,headers,body:JSON.stringify({error:'Password must be at least 6 characters.'})};const lookup=await store.get(`username/${u}`,{type:'json',consistency:'strong'});
if(action==='signup'){if(lookup?.id)return{statusCode:409,headers,body:JSON.stringify({error:'That username is taken.'})};const id=crypto.randomUUID(),pw=hashPassword(password),now=Date.now();const user={id,username:u,displayName:String(body.displayName||u).trim().slice(0,30)||u,avatar:'🎮',bio:'',customStatus:'',banner:'midnight',favoriteGame:'',badges:[],pw,createdAt:now,settings:{appearOffline:false,showActivity:true}};await store.setJSON(`user/${id}`,user);await store.setJSON(`username/${u}`,{id});const token=sign({sub:id,u,exp:Math.floor(Date.now()/1000)+60*60*24*30});return{statusCode:200,headers,body:JSON.stringify({token,user:{id,username:u,displayName:user.displayName,avatar:user.avatar}})};}
if(action==='login'){if(!lookup?.id)return{statusCode:401,headers,body:JSON.stringify({error:'Wrong username or password.'})};const user=await store.get(`user/${lookup.id}`,{type:'json',consistency:'strong'});if(!user?.pw||!verify(password,user.pw.salt,user.pw.hash))return{statusCode:401,headers,body:JSON.stringify({error:'Wrong username or password.'})};const token=sign({sub:user.id,u:user.username,exp:Math.floor(Date.now()/1000)+60*60*24*30});return{statusCode:200,headers,body:JSON.stringify({token,user:{id:user.id,username:user.username,displayName:user.displayName,avatar:user.avatar}})};}
return{statusCode:400,headers,body:JSON.stringify({error:'Unknown action'})};}catch(e){console.error('social-auth',e);return{statusCode:500,headers,body:JSON.stringify({error:e.message?.includes('SECRET')?e.message:'Account service unavailable.'})};}};
